### ISSUE TITLE
The img in the README doesn't work

### ISSUE THREAD

**Issue by jlandure** [resourcepool/takahoot#2]
Hi ! 👋 
This url `https://github.com/resourcepool/takahoot/blob/master/assets/takahoot-on-stand.jpg` does a 404.
Please update the image or the README. 👍

**Comment by loicortola** [comment]
Hi Julien ! Thanks, will take a look :)
The repo hasn't been updated since French confinment started hahaha :)

Le jeu. 23 avr. 2020 à 08:56, Julien Landuré <notifications@github.com> a
écrit :

**Comment by loicortola** [comment]
Links updated, now images are working again.
We will update the tutorial during May :)
Thanks for the issue !
